#pragma once

#define ZIB_INTERNAL_CONCAT_HELPER(a, b) a##b
#define ZIB_INTERNAL_STRINGIFY_HELPER(x) #x

#define ZIB_CONCAT(a, b) ZIB_INTERNAL_CONCAT_HELPER(a, b)
#define ZIB_STRINGIFY(x) ZIB_INTERNAL_STRINGIFY_HELPER(x)
