name: Custom Package

on:
  push:
    branches:
      - asset_resolver
  workflow_dispatch:
    inputs:
        houdini-version:
            description: 'Houdini version to build for'
            required: true
            default: '21.0'
        houdini-build:
            description: 'Houdini build to build against (e.g. "123")'
            required: true
        houdini-win-x64-architecture:
            description: 'Houdini architecture to use for Windows x64 build'
            required: true
            default: 'win64-vc143'
        houdini-linux-x64-architecture:
            description: 'Houdini architecture to use for Linux x64 build'
            required: true
            default: 'linux_x86_64_gcc11.2'
        houdini-mac-x64-architecture:
            description: 'Houdini architecture to use for macOS x64 build'
            required: true
            default: 'macosx_x86_64_clang15'
        houdini-mac-arm64-architecture:
            description: 'Houdini architecture to use for macOS x64 build'
            required: true
            default: 'macosx_arm64_clang15'
        
jobs:
  build-windows-x64:
    name: Build ZibraVDB for Houdini (Windows-x64)
    runs-on: windows-latest
    steps:

    - name: Sync
      uses: actions/checkout@v4

    - name: Install Houdini
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        python -m venv actions/install_houdini/venv
        .\actions\install_houdini\venv\Scripts\Activate.ps1
        pip install -r actions/install_houdini/requirements.txt
        python actions/install_houdini/install_houdini.py --version "${{ inputs.houdini-version }}" --build "${{ inputs.houdini-build }}" --platform "${{ inputs.houdini-win-x64-architecture }}"
      env:
        HOUDINI_CLIENT_ID: ${{ secrets.HOUDINI_CLIENT_ID }}
        HOUDINI_SECRET_KEY: ${{ secrets.HOUDINI_SECRET_KEY }}

    - name: Configure Cmake
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: cmake -S . -B build -G "Visual Studio 17 2022" -DZIBRAVDB_OUTPUT_PATH=${{ github.workspace }}\package
      env:
        HFS: C:\Houdini

    - name: Build Release
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        cmake --build build --config Release
        cmake --build build --config Release --target zibraVDBResolver

    - name: Repack HDA into Binary format
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        C:\Houdini\bin\hotl.exe -l ${{ github.workspace }}\package\otls\zibravdb_filecache.1.0.hda ${{ github.workspace }}\package\otls\zibravdb_filecache.1.0.hda.2
        Remove-Item -Recurse -Force ${{ github.workspace }}\package\otls\zibravdb_filecache.1.0.hda
        Move-Item -Path ${{ github.workspace }}\package\otls\zibravdb_filecache.1.0.hda.2 -Destination ${{ github.workspace }}\package\otls\zibravdb_filecache.1.0.hda

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZibraVDBForHoudini-Windows-x64
        path: package
        if-no-files-found: error

  build-linux-x64:
    name: Build ZibraVDB for Houdini (Linux-x64)
    runs-on: [self-hosted, Linux, X64, houdini]
    steps:

    - name: Sync
      uses: actions/checkout@v4

    - name: Install Houdini
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        python3 -m venv actions/install_houdini/venv
        ./actions/install_houdini/venv/bin/Activate.ps1
        pip3 install -r actions/install_houdini/requirements.txt
        python3 actions/install_houdini/install_houdini.py --version "${{ inputs.houdini-version }}" --build "${{ inputs.houdini-build }}" --platform "${{ inputs.houdini-linux-x64-architecture }}"
      env:
        HOUDINI_CLIENT_ID: ${{ secrets.HOUDINI_CLIENT_ID }}
        HOUDINI_SECRET_KEY: ${{ secrets.HOUDINI_SECRET_KEY }}

    - name: Configure Cmake
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: cmake -S . -B build -G "Ninja Multi-Config" -DZIBRAVDB_OUTPUT_PATH=${{ github.workspace }}/package

    - name: Build Release
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        cmake --build build --config Release
        cmake --build build --config Release --target zibraVDBResolver

    - name: Repack HDA into Binary format
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        /opt/hfs/bin/hotl -l ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2
        Remove-Item -Recurse -Force ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda
        Move-Item -Path ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2 -Destination ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZibraVDBForHoudini-Linux-x64
        path: package
        if-no-files-found: error

    - name: Cleanup environment
      shell: pwsh
      run: Remove-Item -Recurse -Force /opt/hfs

  build-macos-arm64:
    name: Build ZibraVDB for Houdini (macOS-arm64)
    runs-on: macos-latest
    concurrency:
      group: macos-arm64-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Sync
      uses: actions/checkout@v4

    - name: Install Houdini
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        python3 -m venv actions/install_houdini/venv
        ./actions/install_houdini/venv/bin/Activate.ps1
        pip3 install -r actions/install_houdini/requirements.txt
        python3 actions/install_houdini/install_houdini.py --version "${{ inputs.houdini-version }}" --build "${{ inputs.houdini-build }}" --platform "${{ inputs.houdini-mac-arm64-architecture }}"
      env:
        HOUDINI_CLIENT_ID: ${{ secrets.HOUDINI_CLIENT_ID }}
        HOUDINI_SECRET_KEY: ${{ secrets.HOUDINI_SECRET_KEY }}
    - name: Configure Cmake
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: cmake -S . -B build -G "Xcode" -DCMAKE_OSX_ARCHITECTURES=arm64 -DZIBRAVDB_OUTPUT_PATH=${{ github.workspace }}/package
      env:
        HFS: /Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Resources

    - name: Build Release
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        cmake --build build --config Release
        cmake --build build --config Release --target zibraVDBResolver

    - name: Apple sign and notarize ZibraVDBForHoudini
      shell: bash
      run: ${{ github.workspace }}/actions/apple/sign_and_notarize_dylib.sh ${{ github.workspace }}/package/dso/ZibraVDBForHoudini.dylib
      env:
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_CERT }}
        DEVELOPER_ID_APPLICATION_PASS: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_PASS }}
        DEVELOPER_ID_APPLICATION_NAME: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_NAME }}
        APPLE_DEVELOPER_TEAM: ${{ secrets.APPLE_DEVELOPER_ZIBRA_AI_TEAM }}
        NOTARIZATION_USER: ${{ secrets.NOTARIZATION_ZIBRA_AI_USER }}
        NOTARIZATION_PASS: ${{ secrets.NOTARIZATION_ZIBRA_AI_PASS }}

    - name: Apple sign and notarize zibraVDBResolver
      shell: bash
      run: ${{ github.workspace }}/actions/apple/sign_and_notarize_dylib.sh ${{ github.workspace }}/package/zibra/0/lib/libzibraVDBResolver.dylib
      env:
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_CERT }}
        DEVELOPER_ID_APPLICATION_PASS: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_PASS }}
        DEVELOPER_ID_APPLICATION_NAME: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_NAME }}
        APPLE_DEVELOPER_TEAM: ${{ secrets.APPLE_DEVELOPER_ZIBRA_AI_TEAM }}
        NOTARIZATION_USER: ${{ secrets.NOTARIZATION_ZIBRA_AI_USER }}
        NOTARIZATION_PASS: ${{ secrets.NOTARIZATION_ZIBRA_AI_PASS }}
      
    - name: Repack HDA into Binary format
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        /Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Resources/bin/hotl -l ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2
        Remove-Item -Recurse -Force ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda
        Move-Item -Path ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2 -Destination ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZibraVDBForHoudini-macOS-arm64
        path: package
        if-no-files-found: error

  build-macos-x64:
    name: Build ZibraVDB for Houdini (macOS-x64)
    runs-on: macos-latest
    concurrency:
      group: macos-x64-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Sync
      uses: actions/checkout@v4

    - name: Install Houdini
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        python3 -m venv actions/install_houdini/venv
        ./actions/install_houdini/venv/bin/Activate.ps1
        pip3 install -r actions/install_houdini/requirements.txt
        python3 actions/install_houdini/install_houdini.py --version "${{ inputs.houdini-version }}" --build "${{ inputs.houdini-build }}" --platform "${{ inputs.houdini-mac-x64-architecture}}"
      env:
        HOUDINI_CLIENT_ID: ${{ secrets.HOUDINI_CLIENT_ID }}
        HOUDINI_SECRET_KEY: ${{ secrets.HOUDINI_SECRET_KEY }}

    - name: Configure Cmake
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: cmake -S . -B build -G "Xcode" -DCMAKE_OSX_ARCHITECTURES=x86_64 -DZIBRAVDB_OUTPUT_PATH=${{ github.workspace }}/package
      env:
        HFS: /Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Resources

    - name: Build Release
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        cmake --build build --config Release
        cmake --build build --config Release --target zibraVDBResolver

    - name: Apple sign and notarize ZibraVDBForHoudini
      shell: bash
      run: ${{ github.workspace }}/actions/apple/sign_and_notarize_dylib.sh ${{ github.workspace }}/package/dso/ZibraVDBForHoudini.dylib
      env:
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_CERT }}
        DEVELOPER_ID_APPLICATION_PASS: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_PASS }}
        DEVELOPER_ID_APPLICATION_NAME: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_NAME }}
        APPLE_DEVELOPER_TEAM: ${{ secrets.APPLE_DEVELOPER_ZIBRA_AI_TEAM }}
        NOTARIZATION_USER: ${{ secrets.NOTARIZATION_ZIBRA_AI_USER }}
        NOTARIZATION_PASS: ${{ secrets.NOTARIZATION_ZIBRA_AI_PASS }}

    - name: Apple sign and notarize zibraVDBResolver
      shell: bash
      run: ${{ github.workspace }}/actions/apple/sign_and_notarize_dylib.sh ${{ github.workspace }}/package/zibra/0/lib/libzibraVDBResolver.dylib
      env:
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_CERT }}
        DEVELOPER_ID_APPLICATION_PASS: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_PASS }}
        DEVELOPER_ID_APPLICATION_NAME: ${{ secrets.DEVELOPER_ID_APPLICATION_ZIBRA_AI_NAME }}
        APPLE_DEVELOPER_TEAM: ${{ secrets.APPLE_DEVELOPER_ZIBRA_AI_TEAM }}
        NOTARIZATION_USER: ${{ secrets.NOTARIZATION_ZIBRA_AI_USER }}
        NOTARIZATION_PASS: ${{ secrets.NOTARIZATION_ZIBRA_AI_PASS }}

    - name: Repack HDA into Binary format
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        /Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Resources/bin/hotl -l ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2
        Remove-Item -Recurse -Force ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda
        Move-Item -Path ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda.2 -Destination ${{ github.workspace }}/package/otls/zibravdb_filecache.1.0.hda

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZibraVDBForHoudini-macOS-x64
        path: package
        if-no-files-found: error

  merge-artifacts:
    name: Merge artifacts
    runs-on: macos-latest
    needs: [build-windows-x64, build-linux-x64, build-macos-arm64, build-macos-x64]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Merge artifacts
        shell: bash
        run: |
          mkdir merged
          mv ZibraVDBForHoudini-Windows-x64/* merged/
          mv ZibraVDBForHoudini-Linux-x64/dso/ZibraVDBForHoudini.so merged/dso/ZibraVDBForHoudini.so
          lipo -create -output merged/dso/ZibraVDBForHoudini.dylib ZibraVDBForHoudini-macOS-arm64/dso/ZibraVDBForHoudini.dylib ZibraVDBForHoudini-macOS-x64/dso/ZibraVDBForHoudini.dylib
          
          # Merge asset resolver libraries
          mkdir -p merged/zibra/0/lib merged/zibra/0/resources
          cp ZibraVDBForHoudini-Linux-x64/zibra/0/lib/zibraVDBResolver.so merged/zibra/0/lib/
          cp ZibraVDBForHoudini-Linux-x64/zibra/0/resources/plugInfo.json merged/zibra/0/resources/
          lipo -create -output merged/zibra/0/lib/libzibraVDBResolver.dylib ZibraVDBForHoudini-macOS-arm64/zibra/0/lib/libzibraVDBResolver.dylib ZibraVDBForHoudini-macOS-x64/zibra/0/lib/libzibraVDBResolver.dylib
      
      - name: Save merged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZibraVDBForHoudini-20_5
          path: merged
          if-no-files-found: error

      - name: Delete partial artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          name: |
            ZibraVDBForHoudini-Windows-x64
            ZibraVDBForHoudini-Linux-x64
            ZibraVDBForHoudini-macOS-arm64
            ZibraVDBForHoudini-macOS-x64
