name: Build

on: [push]

jobs:
  select-houdini-version:
    name: Select houdini version
    runs-on: ubuntu-latest
    outputs:
      houdini-build-20-5: ${{ steps.select_houdini_build.outputs.houdini_build_20_5 }}
      houdini-build-21-0: ${{ steps.select_houdini_build.outputs.houdini_build_21_0 }}
    strategy:
      fail-fast: false
      matrix:
        houdini-version: ["20.5", "21.0"]

    steps:
      - name: Sync
        uses: actions/checkout@v4

      - name: Select Houdini build
        id: select_houdini_build
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          python3 -m venv actions/houdini/venv
          ./actions/houdini/venv/bin/Activate.ps1
          pip3 install -r actions/houdini/requirements.txt
          python3 actions/houdini/select_build.py --product houdini --version ${{ matrix.houdini-version }} --platforms win64-vc143 macosx_arm64_clang15.0 macosx_x86_64_clang15.0 linux_x86_64_gcc11.2 --verbose
        env:
          HOUDINI_CLIENT_ID: ${{ secrets.HOUDINI_CLIENT_ID }}
          HOUDINI_SECRET_KEY: ${{ secrets.HOUDINI_SECRET_KEY }}
    
  build-plugin:
    needs: select-houdini-version
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64 Houdini 20.5
            runner: windows-latest
            generator: Visual Studio 17 2022
            houdini-version: "20.5"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-20-5 }}
            houdini-platform: win64-vc143
            python-command: python
            additional-config-args: 
          - name: Windows x64 Houdini 21.0
            runner: windows-latest
            generator: Visual Studio 17 2022
            houdini-version: "21.0"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-21-0 }}
            houdini-platform: win64-vc143
            python-command: python
            additional-config-args: 

          - name: Linux x64 Houdini 20.5
            runner: [self-hosted, Linux, X64, houdini]
            generator: Ninja Multi-Config
            houdini-version: "20.5"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-20-5 }}
            houdini-platform: linux_x86_64_gcc11.2
            python-command: python3
            additional-config-args: 
          - name: Linux x64 Houdini 21.0
            runner: [self-hosted, Linux, X64, houdini]
            generator: Ninja Multi-Config
            houdini-version: "21.0"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-21-0 }}
            houdini-platform: linux_x86_64_gcc11.2
            python-command: python3
            additional-config-args: 

          - name: macOS arm64 Houdini 20.5
            runner: macos-14
            generator: Xcode
            houdini-version: "20.5"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-20-5 }}
            houdini-platform: macosx_arm64_clang15.0
            python-command: python3
            additional-config-args: -DCMAKE_OSX_ARCHITECTURES=arm64
          - name: macOS arm64 Houdini 21.0
            runner: macos-14
            generator: Xcode
            houdini-version: "21.0"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-21-0 }}
            houdini-platform: macosx_arm64_clang15.0
            python-command: python3
            additional-config-args: -DCMAKE_OSX_ARCHITECTURES=arm64

          - name: macOS x64 Houdini 20.5
            runner: macos-14
            generator: Xcode
            houdini-version: "20.5"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-20-5 }}
            houdini-platform: macosx_arm64_clang15.0
            python-command: python3
            additional-config-args: -DCMAKE_OSX_ARCHITECTURES=x86_46
          - name: macOS x64 Houdini 21.0
            runner: macos-14
            generator: Xcode
            houdini-version: "21.0"
            houdini-build: ${{ needs.select-houdini-version.outputs.houdini-build-21-0 }}
            houdini-platform: macosx_arm64_clang15.0
            python-command: python3
            additional-config-args: -DCMAKE_OSX_ARCHITECTURES=x86_46
    runs-on: ${{ matrix.runner }}
    name: Build ${{ matrix.name }}

    steps:
      - name: Sync
        uses: actions/checkout@v4

      - name: TEST WIP
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          Write-Output WIP
          Write-Output Target Houdini ${{ matrix.houdini-version }}.${{ matrix.houdini-build }} ${{ matrix.houdini-platform }}
        